# Generated by Django 4.1.7 on 2023-03-25 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_favourite',
            field=models.ManyToManyField(related_name='favourite_adv', to=settings.AUTH_USER_MODEL),
        ),
    ]
